name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

  test:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

  complete:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Complete Job
        run: echo "All tests completed successfully!"
